name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu, windows]
    runs-on: ${{matrix.os}}-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.21.1'
        cache: false
    - uses: ./
    - run: go install -v github.com/rclone/rclone@latest
